#Problem 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.

x = [1, 2]
i = 0
while (i<4000000):
    i = x[-1] + x[-2]
    if (i<4000000):
        x = x + [i]

even = [j for j in x if (j%2==0)]
answer = sum(even)
print(answer)
